### PR TITLE
Embeddings with hnswlib

### PR DESCRIPTION
**Pull request by jaigouk**
there are multiple options for embeddings but most of them are paid versions. and recommended requirement for milvus is [32GB ram for standalone version](https://milvus.io/docs/prerequisite-helm.md). I wanted to start with hnswlib. 

changes

- added embeddings/document
- added embeddings/in_memory_docstore
- added embeddings/split_text
- added embeddings/hnswlib/save_to_hnswlib

why?

- without vector store databases, we can store hnswlib based file for  similarity search

### CODE REVIEW

**Review by francis — COMMENTED** [review]
This looks great. Is it OK if I merge now, or are you still reviewing?

**Comment by jaigouk** [comment]
I want to add integration specs and confirm the search. after this, i wish to add pgvector or redis embeddings. so i wish to clean the up embeddings directory.

**Comment by jaigouk** [comment]
ready for review @francis when you have time, please take a look.

**Comment by francis** [comment]
This has the same problem as the other PR that you fixed. Can you put that work here to support the other rubies so that these tests pass, please?

**Comment by francis** [comment]
@jaigouk - did you get a chance to add the other rubies support?

Also, I'm trying to come up with a nice demo of this ability. Maybe something along the lines of this - https://github.com/hwchase17/notion-qa?

**Comment by jaigouk** [comment]
I will rebase and check

**Comment by jaigouk** [comment]
try to resolve https://github.com/BoxcarsAI/boxcars/issues/13 with Hnswlib

- [x] add Notion_DB folder to notebooks folder
- [ ] change  doc_text_file_path argument to json_doc_file_path and make it optional since it is only for testing and debugging purpose
- [ ] Hnswlib::BuildVectorStore.call should return the instance without calling openAI API if there are existing files. force_update option would be one way to avoid it.

**Review by francis — APPROVED** [review]
Thanks @jaigouk 👍 

I think I will take this as is, but later reduce the size of the test notion site.

**Comment by obie** [comment]
hey folks, just wanted to point you in the direction of Marqo, which I've been using in my own prototypes as a vector DB with built-in generation of embedding and ability to run easily as docker instance. https://www.marqo.ai/

**Pull request merged**
